---
version: '2.4'
services:
  nats-streaming-1:
    hostname: nats-streaming-1
    container_name: nats-streaming-1
    command:
      - "--cluster"
      - "nats://0.0.0.0:6222"
      - "--cluster_id"
      - "nats-streaming"
      - "--clustered"
      - "--cluster_bootstrap"
      - "--cluster_log_path"
      - "/data/log"
      - "--cluster_node_id"
      - "nats-streaming-1"
      - "--cluster_raft_logging"
      - "--debug"
      - "--dir"
      - "/data/msg"
      - "--http_port"
      - "8222"
      - "--port"
      -  "4222"
      - "--store"
      - "file"
      - "--stan_debug"
      - "--hb_interval"
      - "2s"
      - "--hb_fail_count"
      - "1"
      - "--hb_timeout"
      - "5s"
    image: nats-streaming:${VERSION_NATS_STREAMING}
    ports:
      - 14222:4222
      - 18222:8222
  nats-streaming-2:
    hostname: nats-streaming-2
    container_name: nats-streaming-2
    command:
      - "--cluster"
      - "nats://0.0.0.0:6222"
      - "--routes"
      - "nats://nats-streaming-1:6222"
      - "--cluster_id"
      - "nats-streaming"
      - "--clustered"
      - "--cluster_log_path"
      - "/data/log"
      - "--cluster_node_id"
      - "nats-streaming-2"
      - "--cluster_raft_logging"
      - "--debug"
      - "--dir"
      - "/data/msg"
      - "--http_port"
      - "8222"
      - "--port"
      -  "4222"
      - "--store"
      - "file"
      - "--stan_debug"
      - "--hb_interval"
      - "2s"
      - "--hb_fail_count"
      - "1"
      - "--hb_timeout"
      - "5s"
    image: nats-streaming:${VERSION_NATS_STREAMING}
    ports:
      - 24222:4222
      - 28222:8222
  nats-streaming-3:
    hostname: nats-streaming-3
    container_name: nats-streaming-3
    command:
      - "--cluster"
      - "nats://0.0.0.0:6222"
      - "--routes"
      - "nats://nats-streaming-1:6222"
      - "--cluster_id"
      - "nats-streaming"
      - "--clustered"
      - "--cluster_log_path"
      - "/data/log"
      - "--cluster_node_id"
      - "nats-streaming-3"
      - "--cluster_raft_logging"
      - "--debug"
      - "--dir"
      - "/data/msg"
      - "--http_port"
      - "8222"
      - "--port"
      -  "4222"
      - "--store"
      - "file"
      - "--stan_debug"
      - "--hb_interval"
      - "2s"
      - "--hb_fail_count"
      - "1"
      - "--hb_timeout"
      - "5s"
    image: nats-streaming:${VERSION_NATS_STREAMING}
    ports:
      - 34222:4222
      - 38222:8222
networks:
  default:
    name: nats-streaming
