---
version: '2.4'
services:
  nats-streaming-1:
    hostname: nats-streaming-1
    container_name: nats-streaming-1
    command:
      - "--cluster"
      - "nats://0.0.0.0:6222"
      - "--cluster_id"
      - "nats-streaming"
      - "--clustered"
      - "--cluster_bootstrap"
      - "--cluster_log_path"
      - "/data/log"
      - "--cluster_node_id"
      - "nats-streaming-1"
      - "--cluster_raft_logging"
      - "--debug"
      - "--dir"
      - "/data/msg"
      - "--http_port"
      - "8222"
      - "--port"
      -  "4222"
      - "--store"
      - "file"
      - "--stan_debug"
      - "--hb_interval"
      - "2s"
      - "--hb_fail_count"
      - "1"
      - "--hb_timeout"
      - "5s"
    image: nats-streaming:${VERSION_NATS_STREAMING}
    ports:
      - 14222:4222
      - 18222:8222
  producer:
    build:
      context: ../
    image: usecase/natsstreaming-client:latestlocal
    hostname: nats-producer
    container_name: nats-producer
    restart: unless-stopped
    depends_on:
      - nats-streaming-1
    environment:
      CLIENT_MODE: "producer"
      CLIENT_ID: "producer-1"
      CLUSTER_ID: "nats-streaming"
      NATS_URL: "nats://nats-streaming-1:4222"
      SUBJECT_NAME: "test"
  consumer:
    build:
      context: ../
    image: usecase/natsstreaming-client:latestlocal
    hostname: nats-consumer
    container_name: nats-consumer
    restart: unless-stopped
    depends_on:
      - nats-streaming-1
    environment:
      CLIENT_MODE: "consumer"
      CLIENT_ID: "consumer"
      CLUSTER_ID: "nats-streaming"
      NATS_URL: "nats://nats-streaming-1:4222"
      SUBJECT_NAME: "test"
      DURABLE_ENABLE: "false"
      SUBSCRIPTION_OPTION: "latest"
networks:
  default:
    name: nats-streaming
